# Generated by CMake 2.8.9

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target maracuja
ADD_LIBRARY(maracuja SHARED IMPORTED)

# Import target "maracuja" for configuration "Debug"
SET_PROPERTY(TARGET maracuja APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(maracuja PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "-lm;-lc"
  IMPORTED_LOCATION_DEBUG "/home/bumuckl/IDP/maracuja/ubuild/lib/libmaracuja.so"
  IMPORTED_SONAME_DEBUG "libmaracuja.so"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
